# Generated by Django 5.1.7 on 2025-03-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_cost', to='store.product'),
        ),
    ]
